on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      
      # Debugging step to verify the value of GITHUB_TOKEN
      - name: Debug GITHUB_TOKEN
        run: echo "GITHUB_TOKEN = ${{ secrets.GITHUB_TOKEN }}"
        
      # Debugging step to verify the value of USERNAME
      - name: Debug USERNAME
        run: echo "USERNAME = ${{ github.repository_owner }}"
        
      - name: Generate GitHub profile 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          GITHUB_TOKEN: ${{ MY_GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
