name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - name: Check for changes
        id: check_changes
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes detected"
            echo "changes=no" >> $GITHUB_ENV
          else
            echo "Changes detected"
            echo "changes=yes" >> $GITHUB_ENV
          fi
      - name: Generate 3D GitHub profile
        if: env.changes != 'yes'
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        if: env.changes == 'yes'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Generated changes"
          git push

